### ISSUE TITLE
Functions in McDonald.py don't work.

### ISSUE THREAD

**Issue by PanTongLin** [Yooootsuba/McDaily#2]
I can log in with Mask and get the token.
But functions in McDonald.py, such as Lottery() and Coupon_List(), only return HTML files whose titles are "Unauthorized Request Blocked".
Maybe the McDonald company changes something today.
It seems that the official APP still works fine.

**Comment by TsaiRongFu** [comment]
作者您好！我是在巴哈姆特發現此篇文章的因為我英文不是非常好所以使用中文來提問~

由於在昨天11/24您的API我在使用時發生了問題出現了錯誤
這是我部屬在Heroku上的程式所出現的log檔

可以發現在McDonald.py檔案裡 def Coupon_List(self):函式中

`self.respones = eval(self.respones)      # Convert string to dictionary`


出現了錯誤

完整錯誤訊息如下
```
coupon_list = Account.Coupon_List()
File "/app/McDonald.py", line 49, in Coupon_List
self.respones = eval(self.respones)      # Convert string to dictionary
File "<string>", line 1
  <HTML>
  ^
SyntaxError: invalid syntax
```


由於我對您的API沒有熟讀所以沒辦法協助修正BUG
不知道您還會持續更新此專案嗎?

**Comment by Yooootsuba** [comment]
> I can log in with Mask and get the token.
> But functions in McDonald.py, such as Lottery() and Coupon_List(), only return HTML files whose titles are "Unauthorized Request Blocked".
> Maybe the McDonald company changes something today.
> It seems that the official APP still works fine.

Since someday, McDonald changed the request header, you can find it by re-capturing the network packet.
If you have saved response to HTML, you can found it caused "Unauthorized Activity Detected" in my API wapper.
I have committed a new commit to fix this which including the new header.

**Comment by Yooootsuba** [comment]
> 作者您好！我是在巴哈姆特發現此篇文章的因為我英文不是非常好所以使用中文來提問~
> 
> 由於在昨天11/24您的API我在使用時發生了問題出現了錯誤
> 這是我部屬在Heroku上的程式所出現的log檔
> 
> 可以發現在McDonald.py檔案裡 def Coupon_List(self):函式中
> 
> `self.respones = eval(self.respones) # Convert string to dictionary`
> 
> 出現了錯誤
> 
> 完整錯誤訊息如下
> 
> ```
> coupon_list = Account.Coupon_List()
> File "/app/McDonald.py", line 49, in Coupon_List
> self.respones = eval(self.respones)      # Convert string to dictionary
> File "<string>", line 1
>   <HTML>
>   ^
> SyntaxError: invalid syntax
> ```
> 
> 由於我對您的API沒有熟讀所以沒辦法協助修正BUG
> 不知道您還會持續更新此專案嗎?

某天麥當勞更新他們的 Request Header ( 重新撈封包發現的 )

我已經提交新的程式碼去修復它了，感謝回報
